[package]
name = "static-tests"
version = "0.1.0"
authors = ["Jan Bujak <j@exia.io>"]
edition = "2018"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
static_test = "0.1"
speedy = { path = ".." }
